/*
This is the index.tsx file inside the state folder.
It defines the Redux state slice for authentication (auth) using the createSlice function from the @reduxjs/toolkit library.

1. Import Statements:
*/
import { createSlice } from "@reduxjs/toolkit";
import { AuthInterface } from "@/api/types";

/*
2. Initial State:
The initialState variable defines the initial state of the auth slice.
It is an object of type AuthInterface, which represents the authentication state.
*/

const initialState: AuthInterface = {
  mode: "light",
  token: null,
};

/*
3. Redux Slice Creation:
The createSlice function is used to create the auth slice.
It takes an object parameter with the following properties:
- name: The name of the slice.
- initialState: The initial state of the slice.
- reducers: An object that contains the reducer functions for updating the state.

The authSlice variable holds the created slice object.
*/
export const authSlice = createSlice({
  name: "auth",
  initialState,
  reducers: {
    /*
    - setMode: A reducer function that updates the mode property of the state with the payload value.
    - setLogin: A reducer function that updates the token property of the state with the payload value.
    - setLogout: A reducer function that sets the token property of the state to null.
    */
    setMode: (state, action) => {
      state.mode = action.payload;
    },
    setLogin: (state, action) => {
      state.token = action.payload.token;
    },
    setLogout: (state) => {
      state.token = null;
    },
  },
});

/*
4. Action Creators:
The authSlice.actions object contains the action creators generated by createSlice for the defined reducers.
In this case, it includes the setMode, setLogin, and setLogout action creators.

5. Default Export:
The authSlice.reducer is the default export of the module, representing the reducer function of the auth slice.
*/

export const { setLogin, setLogout, setMode } = authSlice.actions;

export default authSlice.reducer;
